### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by teekaytech** [teekaytech/HTML-CSS-capstone-project#1]

**Comment by mariosknl** [comment]
Great job so far. A suggestion that might be help you out is to set the font-size in the reset section to 62.5%. If you set it like this 1rem will be equal to 10px. If you make this you will have to make some adjustments in order to have it as you have it now but it might help you. Since you are using bootstrap remember what you did with your project and by that I mean probably you can replace some of the css properties into classes. Think about that.

**Comment by frankopkusianwar** [comment]
Great job so far and also good work on using variables in your CSS file, this will work well for maintainability. However, I have a suggestion
- you could consider not including the bootstrap script links at the bottom of the HTML file since they are not operational
